### ISSUE TITLE
Check dependencies of jobsub_lite RPM

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#18]
When I tried to install the jobsub_lite RPM on a fresh node, I found that I had to install a number of other RPMs to make it work.  Add these as dependencies in the spec file.  Partial list includes:

voms-clients, globus-gssapi-gsi, osg-ca-certs, vo-client

**Comment by marcmengel** [comment]
Once we add the tracing stuff, the list of dependencies adds:
python3-opentelemetry-exporter-jaeger-thrift 
and its 9 dependences...

**Comment by shreyb** [comment]
We've solved this for 1.0, so we should review this in the near future.

**Comment by shreyb** [comment]
I think this is done.  I'll check by installing the RPM on a fresh machine, and if it works (by pulling in all necessary dependencies), we'll call it done.

**Comment by shreyb** [comment]
Confirmed that following the installation instructions here pulls in all the needed dependencies to install jobsub_lite and successfully submit a job.

https://fifewiki.fnal.gov/wiki/Jobsub_lite_Installation_Instructions
