### ISSUE TITLE
make proxy requirement optional for job submission

### ISSUE THREAD

**Issue by vitodb** [fermitools/jobsub_lite#270]
The CI has a use case where the proxy provided is shorter that 167h and there is no kerberos ticket available to get a longer proxy.
I'd like to have an option to opt out for the proxy requirement.
If the submission happens with this option enabled, a currently available proxy, even if with short lifetime, is sent to the job, it would be fine.

**Comment by shreyb** [comment]
Started work on this.  Underlying library code done.  Just need to make changes to callers so they can support getting proxy, token, or both.

**Comment by shreyb** [comment]
@marcmengel - I'm hoping to have this done today or tomorrow, since I'm on vacation next week.

**Comment by shreyb** [comment]
Pretty much done.  All unit tests pass.  I want to do the following "basic" tests before opening a PR for it:

- [ ] Basic submit (done [2472079.0@jobsub05.fnal.gov](https://landscape.fnal.gov/lens/view/job/2472079.0@jobsub05.fnal.gov/r/summary))
- [ ] Basic Submit, Token-only
- [ ] Basic submit, proxy-only
- [ ] Basic submit, invalid auth method (DONE)
- [ ] Basic submit with file transfer
- [ ] Basic submit with file transfer, token-only
- [ ] Basic submit with file transfer, proxy-only

**Comment by shreyb** [comment]
Some small KeyErrors with the proxy-only submission.  I got it to work, but I want to reexamine where we rely on BEARER_TOKEN_FILE being set.

**Comment by shreyb** [comment]
Fixed all errors, and all unit tests and submissions as detailed above work.  Will wait until jobs run to make sure that correct credentials land in job.

Bash history to detail my submits in tests:

```
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug file:///usr/bin/sleep 300
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug --auth-methods token file:///usr/bin/sleep 300
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug --auth-methods proxy file:///usr/bin/sleep 300
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug --auth-methods proxy,token file:///usr/bin/sleep 300
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug --auth-methods proxy,token,willfail file:///usr/bin/sleep 300
 cd ~/FileUploadTests/
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug -f dropbox:///home/sbhat/FileUploadTests/testfile file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug -f dropbox:///home/sbhat/FileUploadTests/testfile --auth-methods token file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug -f dropbox:///home/sbhat/FileUploadTests/testfile --auth-methods proxy file:///home/sbhat/FileUploadTests/dash-f-dropbox.sh
 cd ~/TestJobs/
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug --auth-methods=token file:///home/sbhat/TestJobs/check_creds.sh
 ~/jobsub_lite/bin/jobsub_submit -G fermilab --debug file:///home/sbhat/TestJobs/check_creds.sh
```

**Comment by shreyb** [comment]
Drafted #459, but will move to "ready" once all the items above are completed.

**Comment by shreyb** [comment]
All above tests are good. Running everything through unit tests one last time, then we're good to go.

**Comment by shreyb** [comment]
All unit tests pass.  Moving PR to review.
