### ISSUE TITLE
Check all schedds when running commands like jobsub_rm

### ISSUE THREAD

**Issue by smitaFnal** [fermitools/jobsub_lite#346]
INC000001148876: user submitted a ticket with:
`jobsub_history` with `jobsub_lite` seems to not work with the `--user` flag

1. jobsub_history isn't fully implemented yet.
2. Check all the schedds when running jobsub query commands (rm, history, hold, etc.)

**Comment by retzkek** [comment]
I renamed this since I felt it kinda buried the lede. Should we spin off another issue for rewriting jobsub_history to use landscape (I think that's what we discussed)?
