### ISSUE TITLE
File transfer failed for target job $(CLUSTER).$(PROC): Failed to receive GoAhead message 

### ISSUE THREAD

**Issue by marcmengel** [fermitools/jobsub_lite#354]
We are having multiple users get this message (looks like mainly on jobsub02?) which gives a submission error on the client side, but the schedd seems to keep the job held "transferring files" for 12 hours and then declare it dead with "Spooling is taking too long".

So it's possible we could tune up timeouts on the client side, not sure which of:
QUERY_TIMEOUT
TRANSFER_TIMEOUT_MULTIPLIER
Q_QUERY_TIMEOUT

might be the right thing to set.  Also not sure how to reproduce it on demand to test...

**Comment by marcmengel** [comment]
More notes:  I thought at first these were correlated with high (i.e. DaemonCore Duty Cycle > 0.95) load on the schedd, but Vito reported at least one 66785384@jobsub02.fnal.gov) that got this error around 17:25 on the 26th, where the duty cycle was consistently under 0.8.  So something else is doing it; need to look maybe at schedd transfer stats(?).

**Comment by marcmengel** [comment]
So I *thought* I saw it lining up, about like this:
![lined_up](https://user-images.githubusercontent.com/254807/228047872-1318f388-b627-41c5-8099-e4699c020244.png)
But on closer examination, it  only kind-of matches at a 24-hour offset (as shown above), **not** a 12-hour one, which then doesn't make sense.   So it's not tied to the duty cycle.

**Comment by marcmengel** [comment]
Anyhow, then we're back to what timeout can we raise to avoid this, or is there something on the server side we can tune...

**Comment by marcmengel** [comment]
Since we cannot reproduce this on demand; one possibility is to bump some timeouts in the config or setup,
(i.e. ` export _condor_TRANSFER_TIMEOUT_MULTIPLIER=4 ` in the /etc/profile.d scripts) and see if  the incidence
decreases.  I've tried that particular variable and run our integration tests; it doesn't seem to *hurt* anything, but it is hard to tell if it *helps*.

**Comment by shreyb** [comment]
@marcmengel @retzkek  - we're not seeing this issue at all anymore, right?

**Comment by marcmengel** [comment]
I haven't seen it in a month or more.  Closing this out.
