### ISSUE TITLE
Multiple submits with same tarfile name from same directory clash

### ISSUE THREAD

**Issue by marcmengel** [fermitools/jobsub_lite#417]
The current code makes a filtered tarfile (with permissions corrected) in the current working directory, with
a name based on the name of the tarfile being submitted.
If two submissions are being made at the same time, with the same tarfile basename, in the same directory,
this causes a clash and the tarfile gets overwritten and removed; this means that one job can
get the other job's tarfile, and that one of the submissions can fail from the tarfile "disappearing"  because
the other jobsub_submit removed it.

**Comment by shreyb** [comment]
@hgreenlee originally reported this issue.

**Comment by shreyb** [comment]
Note:  This also sounds like an old ticket we got from mu2e:  ServiceNow ticket INC000001150554.
