### ISSUE TITLE
Add link to File Transfers documentation in helptext for -f, --tar-file-name

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#427]
Rob Kutschke requested that we add this link to the help text for the `-f` and the `--tar-file-name` flags:

https://fifewiki.fnal.gov/wiki/File_Transfers_in_jobsub_lite

**Comment by shreyb** [comment]
So on second thought, I don't want the source code to have any links to fifewiki, since that's meant for FNAL users only.  Rather, I'll duplicate that page on the Github wiki, and then put the github link in the helptext.

**Comment by retzkek** [comment]
I really don't like wiki content being duplicated, unless you have a mechanism to keep them in sync. If you want in on GitHub, fine, but please move it and make the FIFE wiki page a link (or delete it and update the links to it).

**Comment by shreyb** [comment]
I agree with this criticism.  My only hangup is that the Fifewiki page has some information that is FIFE-specific, and I tried to take that out of the github version.

Perhaps I can put a warning at the top of the FIFEWiki page saying that any further updates to that particular page will be made on Github and supply the link?  What do you think?

**Comment by shreyb** [comment]
> Maybe we should make the fifewiki one contain ONLY the FIFE-specific details, and have a link to the github page for general info?

I like that idea too.  Let me try that real quick.

**Comment by shreyb** [comment]
How does this look?

https://fifewiki.fnal.gov/wiki/File_Transfers_in_jobsub_lite

**Comment by marcmengel** [comment]
That looks good; we should remember though to remove the "What follows here is the ..." and following text later
on so it doesn't confuse people later.

**Comment by shreyb** [comment]
Should I just get rid of that now?

**Comment by marcmengel** [comment]
I think yes, go ahead and drop the old text.

--
Marc W. Mengel
Computer Services Senior Developer

Data Management and Applications
Fermi National Accelerator Laboratory
630 840 8256 office
www.fnal.gov
<https://email.fnal.gov/owa/redir.aspx?C=JkVsWjSyHEuWV2kFJWNPyC9OyMKf7dEIp_yxPk9yfhfadE3mdLfI6T8Ztf8BVaJjzoIe8oJ5H0M.&URL=http%3a%2f%2fwww.fnal.gov>
Connect with us!
Newsletter<https://email.fnal.gov/owa/redir.aspx?C=-29AtpIe40SAvGF4aiNr86KvVjap7dEIuxIdg8Q5bYa9sT7QTFVhxhVnl8zwXkEuBSuAQLRkEfg.&URL=http%3a%2f%2fwww.fnal.gov%2fpub%2ftoday> | Facebook<https://email.fnal.gov/owa/UrlBlockedError.aspx> | Twitter<https://email.fnal.gov/owa/redir.aspx?C=-29AtpIe40SAvGF4aiNr86KvVjap7dEIuxIdg8Q5bYa9sT7QTFVhxhVnl8zwXkEuBSuAQLRkEfg.&URL=https%3a%2f%2ftwitter.com%2fFermilabToday>
________________________________
