### ISSUE TITLE
Alternative term for jobsub's `--blacklist`

### ISSUE THREAD

**Issue by namrathaurs** [fermitools/jobsub_lite#439]
Per RITM1766359, user is requesting for an alternative term to the existing jobsub term `--blacklist`. Following is the description from the user request:

> While testing the fix to INC000001151396 regarding jobsub --blacklist,
> it occurred to me that blacklist seems to be a racist term.
> 
> I found a confirming opinion at
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/
>    regarding the publishing business
>
> There are alternates suggested at
>    https://practicalesg.com/2021/09/say-this-instead-blacklist-blackball-blackmail-black-market-etc/
>     
> Please consider an unoffensive alternate like 
> --block  or --blocklist or --deny .
>
> The offensive option could be retained, hidden, for compatibility.

**Comment by arkreymer** [comment]
Thanks for setting this issue up !

Another term that could be used would be  --avoid 
It is worth thinking this through a bit to find an appropriate term.

**Comment by retzkek** [comment]
A couple years ago we changed the name of the [global configuration](https://fife-service.fnal.gov/blocklist.txt) to blocklist, so that would be consistent.

**Comment by shreyb** [comment]
Although I do like `--avoid` and `--deny` (--deny would probably fit better here), I'm ultimately in favor of `--blocklist` as well, for the same reason @retzkek said.  It also seems to be emerging as a standard (adopted by SAP in cases similar to this).

Thanks for raising this issue, @arkreymer.
