### ISSUE TITLE
Ignore --maxConcurrent if --maxConcurrent m  -N  n and n < m 

### ISSUE THREAD

**Issue by marcmengel** [fermitools/jobsub_lite#440]
Some users are including --maxConcurrent  10000 in all submissions, which is launching DAGs all the time, 
even when doing -N 1 jobs...  We can basically ignore the -maxConcurrent in this case, which will reduce 
the number of DAGs and make debugging those jobs when they go wrong easier.

**Comment by shreyb** [comment]
Do this before #438, since it's easier and fixes the underlying user issues.
