### ISSUE TITLE
When using  multiple `--append_condor_requirements` options, only the last one is honored

### ISSUE THREAD

**Issue by vitodb** [fermitools/jobsub_lite#461]
INC000001156705 shows that when using  multiple `--append_condor_requirements` options, only the last one is honored
The submission uses the following options
```
--append_condor_requirements='(TARGET.CpuFamily==6)' \
--append_condor_requirements='(TARGET.HAS_SINGULARITY=?=true)' \
```
and the [JDF](https://landscape.fnal.gov/lens/view/job/2806822.7@jobsub05.fnal.gov/file/simple.cmd) created for the submission is missing the TARGET.CpuFamily requirement.

I confirmed this checking different combination of `--append_condor_requirements` options and submitting with `-n` option to check the JDF without submitting real jobs.

**Comment by shreyb** [comment]
Looks like @vitodb  is right - Here we just store the value of the `--append_condor_requirements` value:

https://github.com/fermitools/jobsub_lite/blob/1c62513fecf5db09e1981559bf82411d51b5b9d6/lib/get_parser.py#L272

And then we don't do anything with that - we just use it as-is in the templates, like here:

https://github.com/fermitools/jobsub_lite/blob/1c62513fecf5db09e1981559bf82411d51b5b9d6/templates/simple/simple.cmd#L73

That certainly seems wrong.  I think we should be saving it as a list, and then using jinja to add a "&&" between each item.

**Comment by shreyb** [comment]
Note:  The original issue was brought up by @rlcee

**Comment by shreyb** [comment]
Confirmed that this is a bug:  the old jobsub_server did indeed support successive `--append-condor-requirements` flags:

https://cdcvs.fnal.gov/redmine/projects/jobsub/repository/revisions/master/entry/lib/groupsettings/JobSettings.py#L589

**Comment by shreyb** [comment]
And indeed, the issue is that `argparse` respects the last value of a repeated argument:

```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo')
_StoreAction(option_strings=['--foo'], dest='foo', nargs=None, const=None, default=None, type=None, choices=None, required=False, help=None, metavar=None)
>>> parser.parse_args(['--foo', 'bar', '--foo', 'baz'])
Namespace(foo='baz')
```

**Comment by shreyb** [comment]
Fix seems to work.  The following jobsub_submit line:

`jobsub_submit -G fermilab -n --append_condor_requirements='(TARGET.CpuFamily==6)' --append_condor_requirements='(TARGET.HAS_SINGULARITY=?=true)'  file:///usr/bin/sleep 300`

Yields the following requirements string in the JDF (note the end of the expression):

`requirements  = target.machine =!= MachineAttrMachine1 && target.machine =!= MachineAttrMachine2 && (isUndefined(DesiredOS) || stringListsIntersect(toUpper(DesiredOS),IFOS_installed)) && (stringListsIntersect(toUpper(target.HAS_usage_model), toUpper(my.DESIRED_usage_model))) && (TARGET.CpuFamily==6) && (TARGET.HAS_SINGULARITY=?=true)`

And job submits successfully.
