### ISSUE TITLE
Add a "jobsub -h" option to list all jobsub commands

### ISSUE THREAD

**Issue by goodenou** [fermitools/jobsub_lite#471]
A request from Heidi Schellman in RITM1845157

Users often don't know which jobsub commands exist.  If there were a jobsub -h (or even jobsub ) that just listed the jobsub commands, that would be very helpful.  Bonus points for having it point to a url for the real documentation.

**Comment by shreyb** [comment]
Noted that this was approved, and that #472 is the corresponding PR.  However, there are some design considerations that @retzkek wants us to consider.

**Comment by shreyb** [comment]
@goodenou, @hschellman:  This feature will go into release 1.5, due out early November.
