### ISSUE TITLE
TRACEPARENT formatting in v1.4 preventing environment variables from being passed to lens

### ISSUE THREAD

**Issue by LTrestka** [fermitools/jobsub_lite#473]
jobsub_lite is not formatting the "TRACEPARENT" environment variable correctly according to condor docs, this causes lens to fail at parsing.

All variables passed into the submission make it to the jobsub logs, and to kibana, but nothing in the list that comes after and including TRACEPARENT can be queried in lens.

ex:
`Environment = "POMS4_CAMPAIGN_STAGE_NAME=dd_sample_campaign_stage_1 GRID_USER=ltrestka TRACEPARENT=\"00-e3131325f54a321cdb504f049bfcac76-3976795c459dbf45-01\" IFDH_DEBUG=1 EXPERIMENT=hypot POMS4_CAMPAIGN_STAGE_ID=2602 CLUSTER=71832400 JOBSUBJOBID=71832400.0@jobsub02.fnal.gov POMS4_CAMPAIGN_NAME=dd_sample_campaign_1 "`
- In this example , only POMS4_CAMPAIGN_STAGE_NAME and GRID_USER would make it to lens.
- Note: I removed some variables to keep it simple, full submission can be seen [here](https://fifemon.fnal.gov/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:'fifebatch-history-*',interval:auto,query:(language:lucene,query:'JobsubJobId:71832400.0@jobsub02.fnal.gov'),sort:!('@timestamp',desc)))

Per the doc:
>Put double quote marks around the entire argument string. This distinguishes the new syntax from the old. The old syntax does not have double quote marks around it. Any literal double quote marks within the string must be escaped by repeating the double quote mark.
https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html (ctrl-f "enviroment")

**Comment by retzkek** [comment]
From what I can tell it's condor that's formatting the environment incorrectly - we actually specify it in the submit script with the "old" format. https://github.com/fermitools/jobsub_lite/blob/master/templates/simple/simple.cmd#L18
