### ISSUE TITLE
Transition from decode_token.sh to htdecodetoken

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#475]
#474 is meant to be a stopgap to help fix certain users' environments.  Since `htdecodetoken` (aka `httokendecode`) is now a standard tool packaged with the `htgettoken` RPM, which is a jobsub_lite dependency, we should replace `decode_token.sh` with a call to `httokendecode`, and then handle any of the JSON parsing in python (for example, to get the scopes of the token for the token-weakening).

**Comment by retzkek** [comment]
Instead of relying on any command-line tool (which is primarily meant for interactive use) can we use the scitokens library directly when working with tokens? https://github.com/scitokens/scitokens
