### ISSUE TITLE
jobsub_q off by one

### ISSUE THREAD

**Issue by LTrestka** [fermitools/jobsub_lite#494]
The total jobs reported by jobsub_q is always one less than the actual total.

$ jobsub_q --version
jobsub_lite version 1.4.1
$ jobsub_q --user=john.doe
JOBSUBJOBID                             OWNER           SUBMITTED     RUNTIME   ST PRIO   SIZE  COMMAND
-1 total; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended

**Comment by shreyb** [comment]
@hgreenlee - this is for the ticket you opened (INC000001162256) in ServiceNow.  Thanks for reporting it!
