### ISSUE TITLE
Empty scitokens keycache file breaks jobsub commands

### ISSUE THREAD

**Issue by retzkek** [fermitools/jobsub_lite#498]
Users have encountered intermittent issues with jobsub commands breaking with an error like `Error: OperationalError: no such table: keycache`. Upon investigation the scitokens keycache database file is empty (zero bytes). I opened scitokens/scitokens#188 but we may have to work around it here as well.

The quick workaround is to `rm ${XDG_CACHE_HOME:-$HOME/.cache}/scitokens/scitokens_keycache.sqllite`

**Comment by retzkek** [comment]
I don't seem to be able to replicate the issue if I set `XDG_CACHE_HOME` to a local filesystem, so maybe that's an alternative workaround. We wouldn't want to change that globally though I don't think.

**Comment by shreyb** [comment]
To summarize the proposal being discussed on Slack now, we could do the following:

1.  Create a scitokens config file (see https://github.com/scitokens/scitokens#configuration), to be distributed with jobsub_lite. 
2. Set the key `cache_location` to `/run/user/$(id -u)` (does this have to be done dynamically?  Should the "config" file thus be dynamically generated in /tmp or something like that?)
3. As the instructions in the link in (1) say, make sure to call `scitokens.set_config("/path/to/scitokens/config.ini")` everywhere we're calling a scitokens function.
