### ISSUE TITLE
Add --gpu flag to jobsub_submit that allows users to request GPUs

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#505]
Currently, if users want to request GPUs, they use the following incantation:

```
jobsub_submit -G <group> --lines='+RequestGPUs=1' <other_args>
```

We should have a flag, `--gpu`, that accepts a number (defaulting to `1`), which will add the `+RequestGPUs` classad to the JDF.

We might also want to build in another flag where the user can specify the kind of GPU, but that's still under discussion (currently, users can specify that using `--lines`, so there's no hurry).

**Comment by retzkek** [comment]
Condor also has `require_gpus` for constraints so we may want a flag for that. 
https://htcondor.readthedocs.io/en/latest/users-manual/submitting-a-job.html#jobs-that-require-gpus
https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html#require_gpus

**Comment by shreyb** [comment]
In the last jobsub project meeting, we finalized the design for this flag.  It should:

* Set both RequestGPUs and request_GPUs  (e.g. request_GPUs = 1)

For now, users should use flag --append-condor-requirements to add GPU requirements, e.g.
	```
	requirements = CUDARuntimeVersion >= 5.5 \
    && (CUDACapability >= 3.0) \
    && (CUDAGlobalMemoryMb >= 1500)
    ```

* So we need to document the above
* We should also be sure to check the condor docs

**Comment by shreyb** [comment]
Created the flag.  Now have to implement the classads.

**Comment by shreyb** [comment]
Classads implemented.  This is ready to test.

**Comment by shreyb** [comment]
Testing notes:

```
[user@submit_node jobsub_lite]$  bin/jobsub_submit -G fermilab --schedd-for-testing=schedd_host --gpu 1  file:///home/user/TestJobs/test_print_ads.sh
Using requested schedd schedd_host
Transferring files to web sandbox...
.....
Submitting job(s).
1 job(s) submitted to cluster 382.
WARNING: the line 'RequestGPUs = 1' was unused by condor_submit. Is it a typo?

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Use job id 382.0@schedd_host to retrieve output
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
```

Maybe `RequestGPUs` needs to be `+RequestGPUs`?  I'll check that.

**Comment by shreyb** [comment]
This job matched to the correct node, but didn't run due to infrastructure issues.  We'll see if those can get fixed today or tomorrow before retesting.

**Comment by shreyb** [comment]
Testing note 2:

```
[user@submit_host jobsub_lite]$  bin/jobsub_submit -G fermilab --schedd-for-testing=schedd@domain --gpu 1  file:///home/user/TestJobs/test_print_ads.sh
...
Using requested schedd schedd@domain
Transferring files to web sandbox...
...
Submitting job(s).
1 job(s) submitted to cluster 409.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Use job id 409.0@schedd@domain to retrieve output
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
```

The warning is gone, but the job still went held due to infrastructure issues.

**Comment by shreyb** [comment]
Unfortunately, our dev schedd isn't hooked up to our GlideinWMS frontend, so the previously submitted job wouldn't run.  I submitted two test jobs today to our production cluster of schedds, and one already ran at a GPU site:

Job `83697089@schedd2` selection of relevant Job  Ad attributes:
```
RequestGPUs = 1
```

Job `83697089@schedd2` selection of relevant Machine Ad attributes:

```
GLIDEIN_GPUS = 1
GPUs = 1
GPUsMemoryUsage = 520.0
GPUs_Capability = 8.0
GPUs_ClockMhz = 1410.0
GPUs_ComputeUnits = 108
GPUs_CoresPerCU = 64
GPUs_DeviceName = "NVIDIA A100-PCIE-40GB"
```

**Comment by shreyb** [comment]
With this successful test, we're ready to open a PR for this.

**Comment by shreyb** [comment]
Note:  Second test job `14678526@schedd5` also ran on a GPU resource, with the proper MachineAds present like above.
