### ISSUE TITLE
Fix cyclic import in lib/condor.py

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#518]
https://github.com/fermitools/jobsub_lite/blob/f222428da0026016d8e156a640256e2f6b99eb38/lib/condor.py#L31

PR #508 introduced a cyclic import in lib/condor.py, and I've currently disabled the `cyclic-import` pylint check on the line indicated above. 

As indicated in #513, we should fix this before we release 1.6, and we should re-enable the `cyclic-import` check to make sure that it's truly resolved.

Steps to reproduce:

1.  Checkout current master (f222428da0)
2. Delete line 31 in lib/condor.py (the line reads `# pylint: disable=cyclic-import`
3. Run pre-commit on all the files:
```
$ pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
mypy (no tests or bin)...................................................Passed
mypy (bin)...............................................................Passed
pylint...................................................................Failed
- hook id: pylint
- exit code: 12

************* Module version
lib/version.py:1:0: R0401: Cyclic import (condor -> submit_support) (cyclic-import)
lib/version.py:1:0: R0401: Cyclic import (condor -> submit_support -> dagnabbit -> get_parser) (cyclic-import)
lib/version.py:1:0: R0401: Cyclic import (condor -> submit_support -> dagnabbit -> get_parser -> pool) (cyclic-import)

------------------------------------------------------------------
Your code has been rated at 9.98/10 (previous run: 9.77/10, +0.21)

black....................................................................Passed
```

**Comment by shreyb** [comment]
@marcmengel I'm assigning this to you since you're the most familiar with the condor.py code and its dependencies.

**Comment by marcmengel** [comment]
Well, the fix is basically to move transfer_sandbox() to it's own python file and import
it into condor.py and submit_support.py from there.   Then we could, if we were feeling really
organizational, move fetch_from_landscape out of bin/jobsub_fetchlog in there too; and maybe move fetch_from_condor out of bin/jobsub_fetchlog into lib/condor.py...

**Comment by shreyb** [comment]
I like the idea of keeping it simple.  As you said, move `transfer_sandbox` into its own file (like `sandbox.py` or something like that) and import it into `condor.py` and `submit_support.py`.

I think the case could be made either way about whether or not the `fetch_from_` functions belong with `transfer_sandbox`, so I'll leave that call up to you.
