### ISSUE TITLE
New condor_vault_storer version

### ISSUE THREAD

**Issue by DrDaveD** [fermitools/jobsub_lite#544]
Please include the `condor_vault_storer` from [HTCONDOR-2232](https://github.com/htcondor/htcondor/pull/2232) in a jobsub_lite release.
Here's a [direct link](https://raw.githubusercontent.com/htcondor/htcondor/32a5b5794979fc439323809bbfa5b4f0e1890f6b/src/condor_credd/condor_credmon_oauth/condor_vault_storer).

**Comment by DrDaveD** [comment]
There was now also an additional change from another PR, both of which are now merged and scheduled for the 23.0.8 condor release.  Use instead [this link](https://raw.githubusercontent.com/htcondor/htcondor/V23_0-branch/src/condor_credd/condor_credmon_oauth/condor_vault_storer).

**Comment by DrDaveD** [comment]
Note that the way to enable verbose mode changes in this new version of condor_vault_storer, because the old way doesn't work with condor 23.  So the method added in #551 should change to setting `_condor_SEC_CREDENTIAL_VAULT_STORER_OPTS` instead of appending to `_condor_SEC_CREDENTIAL_STORER` at the same time as this is issue is addressed.

**Comment by shreyb** [comment]
Thanks for drawing our attention to that, Dave.

We discussed this at the jobsub meeting, and the plan is to do this entire transition in phases:

1) Do what Dave requested here.  This issue will become the first item in a new project I'll open for jobsub_lite.  Target this for release 1.8, due out in April or May.
2) Sometime between now and June 30, 2024, all of the interactive nodes will be upgraded to AL9.  At that point, condor will be upgraded to at least 2023.0
3) Once [HTCONDOR-2232](https://github.com/htcondor/htcondor/pull/2232) is in a condor release (probably late Summer to early Fall of 2024), upgrade interactive nodes to that version.
4) Wait until [POMS-16](https://github.com/fermitools/poms/issues/16) is finished.
5) Put out a test release where we remove condor_vault_storer from the jobsub repository.
6) Once we are satisfied with testing, put out a final release with condor_vault_storer removed from the jobsub repository.  At that point, we will expect condor_vault_storer to come from condor.
