### ISSUE TITLE
If spack can't find an IFDH version, just use current

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#553]
On this line:

https://github.com/fermitools/jobsub_lite/blob/fdb71444528ac5ec563dd0c6254f2a202fc9b5cb/templates/simple/simple.sh#L175

if spack can't find an IFDH, the ifdh.sh script just exits.  However, with the move to spack and AL9, there are limits to the previous versions we want to put in spack.  Mu2e, while testing 1.7-rc1, found that using IFDH 2_6_18 was too old, and thus their files didn't transfer in before the job started, as well as the fact that their logs couldn't get transferred out.

The way this should work is that in our ifdh.sh script, if we can't find the IFDH version the user wants, just use current.  This will allow us to at least transfer dropbox files into the job and logs out of the job.  We think this should be safe because we will not be changing the user-given environment variable `IFDH_VERSION` (which presumably the user is using in their job), and ifdh.sh is only used by the jobsub wrapper for the initial file transfer in and job log transfer out.

**Comment by shreyb** [comment]
@kherner had a good idea in addition.  If we have to fall back to the current version of IFDH in this case, we should `echo` a warning that we're doing that.

**Comment by marcmengel** [comment]
So I'm doing it so that if you submit with `-e IFDH_VERSION=v_no_such_thing`  you get, in the .err file:
```
==> Error: No such environment: 'ifdh_env_almalinux9_v_no_such_thing'
Falling back to current ifdhc
```
The first line is from Spack when it can't find the version they asked for, that second is informational.

**Comment by marcmengel** [comment]
https://landscape.fnal.gov/lens/view/job/77377726.0@jobsub02.fnal.gov/stderr :
```
==> Error: No such environment: 'ifdh_env_almalinux9_v_no_such_thing'
Falling back to current ifdhc
==>Error: No such environment: 'ifdh_env_almalinux9_v_no_such_thing'
Falling back to current ifdhc
```

**Comment by shreyb** [comment]
Love it.  Maybe we say "Falling back to current ifdhc for this operation" or something like that?
